apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lineoa-ibmdtrun-data
  namespace: __NAMESPACE__
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lineoa-ibmdtrun-public
  namespace: __NAMESPACE__
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
